# Default values for User-Provided Service Broker
# Image to use
image: neunnsy/oracle-service-broker:v0.0.1
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
